id: I26342640
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:24:36+00:00'
last_modified: '2022-06-08T02:07:11.858191+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17175
  title: ཁ་ཆེའི་གཡུ་རྫོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2EA4:
      image_group_id: I1KG18042
      title: ''
      total_pages: 358
      order: 1
      base_file: 2EA4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
