id: P004585
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 11:42:55.204757
source_metadata:
  id: bdr:W1KG17175
  title: ཁ་ཆེའི་གཡུ་རྫོང་།
  author: ''
  volumes:
    2b338d9f29584502a14f32578636648e:
      image_group_id: I1KG18042
      title: ''
      volume_number: 1
      total_pages: 358
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
